"use client";
import { Clock3, GripVertical, MapPin, Phone, Truck } from "lucide-react";
import type { buildDeliveryGroups } from "@/lib/delivery";
import { formatUsd } from "@/lib/formatters";
import { memoryLabel } from "@/lib/purchase-details";
import styles from "./DeliveryScreen.module.css";
type Group = ReturnType<typeof buildDeliveryGroups>[number];
export default function SupplierDeliveries({ groups, loading, onMove }: { groups: Group[]; loading: boolean; onMove: (from: number, to: number) => void }) {
 return <div className={styles.board}>{!groups.length ? <div className={styles.empty}><Truck size={30}/><h2>{loading ? "Cargando pedidos…" : "No hay tarjetas por generar"}</h2><p>Los pedidos generados pasan a Pendientes de recepción.</p></div> : groups.map((group,index)=><article className={styles.card} aria-label={`Pedido de ${group.name}`} key={group.supplierId} draggable onDragStart={e=>e.dataTransfer.setData("text/plain",String(index))} onDragOver={e=>e.preventDefault()} onDrop={e=>onMove(Number(e.dataTransfer.getData("text/plain")),index)}><header className={styles.cardHeader}><div className={styles.identity}><span className={styles.drag} title="Arrastrar para reordenar"><GripVertical size={19}/></span><div><h2>{group.name}</h2><small>{group.lines.reduce((sum,line)=>sum+line.quantity,0)} unidades</small></div></div><div className={styles.supplierMeta}><span className={styles.schedule}><Clock3 size={14}/>{group.from && group.until ? `${group.from} – ${group.until}` : group.from ? `Desde ${group.from}` : group.until ? `Hasta ${group.until}` : "Horario sin definir"}</span><div className={styles.contact}><span><MapPin size={13}/>{group.address||"Dirección sin cargar"}</span><span><Phone size={13}/>{group.phone||"Teléfono sin cargar"}</span></div></div></header><div className={styles.items}>{group.lines.map(line=><div className={styles.item} key={line.id}><div><strong>{line.product}</strong><small>Pedido #{line.orderId}</small></div><div><span className={styles.label}>Características</span>{[memoryLabel(line.ram,line.rom),line.variant,line.color].filter(Boolean).join(" · ")}</div><div className={styles.price}><strong>{formatUsd(line.cost)}</strong><small>×{line.quantity}</small></div></div>)}</div></article>)}</div>;
}
